# Generated by Django 3.1 on 2020-08-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='Doctor_id',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Specialization',
            field=models.TextField(blank=True),
        ),
    ]
